import { EventTypeConfig } from '../types/calendar';

export const eventTypeConfig: Record<EventType, EventTypeConfig> = {
  work_shift: {
    label: 'Work Shift',
    color: '#10b981',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    icon: 'briefcase',
    requiresApproval: false,
    allowRecurring: true,
  },
  sick_leave: {
    label: 'Sick Leave',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    icon: 'heart',
    requiresApproval: true,
    allowRecurring: false,
  },
  casual_leave: {
    label: 'Casual Leave',
    color: '#f59e0b',
    bgColor: '#fffbeb',
    borderColor: '#fef3c7',
    icon: 'coffee',
    requiresApproval: true,
    allowRecurring: false,
  },
  vacation: {
    label: 'Vacation',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    icon: 'plane',
    requiresApproval: true,
    allowRecurring: false,
  },
  holiday: {
    label: 'Holiday',
    color: '#8b5cf6',
    bgColor: '#f3e8ff',
    borderColor: '#ddd6fe',
    icon: 'gift',
    requiresApproval: false,
    allowRecurring: true,
  },
  meeting: {
    label: 'Meeting',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    icon: 'users',
    requiresApproval: false,
    allowRecurring: true,
  },
  deadline: {
    label: 'Deadline',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    icon: 'clock',
    requiresApproval: false,
    allowRecurring: false,
  },
  company_event: {
    label: 'Company Event',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    borderColor: '#fce7f3',
    icon: 'calendar',
    requiresApproval: false,
    allowRecurring: true,
  },
  training: {
    label: 'Training',
    color: '#84cc16',
    bgColor: '#f7fee7',
    borderColor: '#d9f99d',
    icon: 'book',
    requiresApproval: true,
    allowRecurring: true,
  },
  interview: {
    label: 'Interview',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#ddd6fe',
    icon: 'user-plus',
    requiresApproval: false,
    allowRecurring: false,
  },
};

export const getEventConfig = (type: EventType) => eventTypeConfig[type];